CREATE TABLE BOARD(
    NO NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(1000),
    UPD_DATE DATE DEFAULT SYSDATE,
    REG_DATE DATE DEFAULT SYSDATE,
    -- VIEWS 조회수 컬럼 조회하기
    VIEWS NUMBER NOT NULL,
    PRIMARY KEY(NO)
    );